version: "3"
services:
    easy-shoes:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        volumes:
            - ./src:/app/src
            - ./ormconfig.json:/app/ormconfig.json
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: easyshoes
        volumes: 
            - /var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            